#!/bin/sh

echo "Kafka path: ".${KAFKA_PATH}

cd ${KAFKA_PATH}

bin/zookeeper-server-start.sh config/zookeeper.properties &
sleep 10

bin/kafka-server-start.sh config/server.properties &
sleep 20

queues=( si-request si-response )

for i in "${queues[@]}"
do
  echo "Running queue:" $i
  bin/kafka-topics.sh --create --zookeeper localhost:2181 --partitions 1 --replication-factor 1 --topic $i &
done
